import { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service",
  robots: { index: true, follow: true },
};

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-cream pb-28">
      <div className="max-w-prose mx-auto px-5 pt-14 pb-8">
        <h1 className="text-2xl font-bold text-brown-dark mb-6">Terms of Service</h1>
        <p className="text-xs text-brown-medium mb-8">Last updated: March 28, 2026</p>

        <div className="prose-sm text-brown-dark space-y-6 text-sm leading-relaxed">
          <section>
            <h2 className="text-base font-semibold mb-2">1. Service Description</h2>
            <p>
              TransTaste (&quot;the Service&quot;) is a mobile web application that uses artificial intelligence
              to analyze restaurant menu images, text, and URLs to provide translations, allergen information,
              flavor profiles, and cultural dining context.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold mb-2">2. Not a Medical Device</h2>
            <p>
              TransTaste is <strong>NOT a medical device, diagnostic tool, or substitute for professional
              medical advice</strong>. All allergen information, dietary flags, and ingredient analysis
              provided by the Service are AI-generated estimates for informational reference only.
            </p>
            <p className="mt-2">
              <strong>You must always confirm allergens and ingredients directly with restaurant staff
              before consuming any food.</strong> Actual ingredients, preparation methods, and cross-contamination
              risks vary by restaurant and cannot be fully determined through menu analysis alone.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold mb-2">3. Limitation of Liability</h2>
            <p>
              The Service is provided &quot;as is&quot; without warranties of any kind. To the maximum extent
              permitted by applicable law, TransTaste and its operators shall not be liable for any direct,
              indirect, incidental, consequential, or special damages arising from your use of the Service,
              including but not limited to allergic reactions, food-related illness, or any health consequences
              resulting from reliance on information provided by the Service.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold mb-2">4. AI-Generated Content</h2>
            <p>
              All translations, allergen warnings, flavor profiles, ingredient lists, fun facts, and
              recommendations are generated by artificial intelligence models. These outputs may contain
              errors, omissions, or inaccuracies. The Service does not guarantee the completeness or
              correctness of any AI-generated content.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold mb-2">5. User Responsibilities</h2>
            <ul className="list-disc pl-5 space-y-1">
              <li>You are responsible for verifying allergen information with restaurant staff</li>
              <li>You acknowledge that AI analysis may not detect all allergens or dietary concerns</li>
              <li>You use the Service at your own risk, particularly regarding food allergies</li>
              <li>You will not rely solely on the Service for life-threatening allergy decisions</li>
            </ul>
          </section>

          <section>
            <h2 className="text-base font-semibold mb-2">6. Payments & Refunds</h2>
            <p>
              Trip Passes and Scan Credits are one-time purchases processed through Stripe.
              Trip Passes expire at the end of their stated duration (7 or 30 days).
              Scan Credits do not expire. Refund requests may be submitted within 7 days of purchase.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold mb-2">7. Changes to Terms</h2>
            <p>
              We may update these Terms from time to time. Continued use of the Service after
              changes constitutes acceptance of the updated Terms.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold mb-2">8. Contact</h2>
            <p>
              Questions about these Terms may be directed to the TransTaste team via the app or website.
            </p>
          </section>
        </div>

        <div className="mt-8 pt-4 border-t border-brown-light/10">
          <Link href="/privacy" className="text-sm text-coral hover:underline">
            Privacy Policy →
          </Link>
        </div>
      </div>
    </main>
  );
}
