"use client";

import Link from "next/link";
import { useTranslation } from "@/lib/i18n";

// Client component for locale-based body rendering. Metadata lives in layout.tsx.

function TermsEn() {
  return (
    <>
      <section>
        <h2 className="text-base font-semibold mb-2">1. Service Description</h2>
        <p>
          TransTaste (&quot;the Service&quot;) is a mobile web application that uses artificial intelligence
          to analyze restaurant menu images, text, and URLs to provide translations, allergen information,
          flavor profiles, and cultural dining context.
        </p>
      </section>

      <section>
        <h2 className="text-base font-semibold mb-2">2. Not a Medical Device</h2>
        <p>
          TransTaste is <strong>NOT a medical device, diagnostic tool, or substitute for professional
          medical advice</strong>. All allergen information, dietary flags, and ingredient analysis
          provided by the Service are AI-generated estimates for informational reference only.
        </p>
        <p className="mt-2">
          <strong>You must always confirm allergens and ingredients directly with restaurant staff
          before consuming any food.</strong> Actual ingredients, preparation methods, and cross-contamination
          risks vary by restaurant and cannot be fully determined through menu analysis alone.
        </p>
      </section>

      <section>
        <h2 className="text-base font-semibold mb-2">3. Limitation of Liability</h2>
        <p>
          The Service is provided &quot;as is&quot; without warranties of any kind. To the maximum extent
          permitted by applicable law, TransTaste and its operators shall not be liable for any direct,
          indirect, incidental, consequential, or special damages arising from your use of the Service,
          including but not limited to allergic reactions, food-related illness, or any health consequences
          resulting from reliance on information provided by the Service.
        </p>
      </section>

      <section>
        <h2 className="text-base font-semibold mb-2">4. AI-Generated Content</h2>
        <p>
          All translations, allergen warnings, flavor profiles, ingredient lists, fun facts, and
          recommendations are generated by artificial intelligence models. These outputs may contain
          errors, omissions, or inaccuracies. The Service does not guarantee the completeness or
          correctness of any AI-generated content.
        </p>
      </section>

      <section>
        <h2 className="text-base font-semibold mb-2">5. User Responsibilities</h2>
        <ul className="list-disc pl-5 space-y-1">
          <li>You are responsible for verifying allergen information with restaurant staff</li>
          <li>You acknowledge that AI analysis may not detect all allergens or dietary concerns</li>
          <li>You use the Service at your own risk, particularly regarding food allergies</li>
          <li>You will not rely solely on the Service for life-threatening allergy decisions</li>
        </ul>
      </section>

      <section>
        <h2 className="text-base font-semibold mb-2">6. Payments & Refunds</h2>
        <p>
          Trip Passes and Scan Credits are one-time purchases processed through Stripe.
          Trip Passes expire at the end of their stated duration (7 or 30 days).
          Scan Credits do not expire. Refund requests may be submitted within 7 days of purchase.
        </p>
      </section>

      <section>
        <h2 className="text-base font-semibold mb-2">7. Changes to Terms</h2>
        <p>
          We may update these Terms from time to time. Continued use of the Service after
          changes constitutes acceptance of the updated Terms.
        </p>
      </section>

      <section>
        <h2 className="text-base font-semibold mb-2">8. Contact</h2>
        <p>
          Questions about these Terms may be directed to the TransTaste team via the app or website.
        </p>
      </section>
    </>
  );
}

function TermsKo() {
  return (
    <>
      <section>
        <h2 className="text-base font-semibold mb-2">1. 서비스 설명</h2>
        <p>
          TransTaste(&quot;본 서비스&quot;)는 인공지능을 이용하여 레스토랑 메뉴 이미지, 텍스트, URL을 분석하고
          번역, 알레르기 정보, 맛 프로파일, 식문화 정보를 제공하는 모바일 웹 애플리케이션입니다.
        </p>
      </section>

      <section>
        <h2 className="text-base font-semibold mb-2">2. 의료기기가 아님</h2>
        <p>
          TransTaste는 <strong>의료기기, 진단 도구 또는 전문 의료 자문의 대체재가 아닙니다</strong>.
          본 서비스가 제공하는 모든 알레르기 정보, 식이 표시, 성분 분석은 정보 참고용으로 AI가 생성한
          추정치입니다.
        </p>
        <p className="mt-2">
          <strong>음식을 섭취하기 전에 반드시 레스토랑 직원에게 직접 알레르기 유발 성분과 재료를
          확인해야 합니다.</strong> 실제 재료, 조리 방법, 교차 오염 위험은 레스토랑마다 다르며 메뉴
          분석만으로는 완전히 파악할 수 없습니다.
        </p>
      </section>

      <section>
        <h2 className="text-base font-semibold mb-2">3. 책임의 제한</h2>
        <p>
          본 서비스는 어떠한 종류의 보증 없이 &quot;있는 그대로&quot; 제공됩니다. 관련 법률이 허용하는
          최대 범위 내에서, TransTaste 및 그 운영자는 본 서비스의 이용으로 인해 발생하는 모든 직접적,
          간접적, 부수적, 결과적 또는 특별한 손해(알레르기 반응, 음식 관련 질병, 본 서비스가 제공한
          정보에 의존하여 발생한 건강상의 결과를 포함하되 이에 한정되지 않음)에 대하여 책임을
          지지 않습니다.
        </p>
      </section>

      <section>
        <h2 className="text-base font-semibold mb-2">4. AI 생성 콘텐츠</h2>
        <p>
          모든 번역, 알레르기 경고, 맛 프로파일, 재료 목록, 흥미로운 사실, 추천은 인공지능 모델에 의해
          생성됩니다. 이러한 결과물은 오류, 누락 또는 부정확한 정보를 포함할 수 있습니다. 본 서비스는
          AI가 생성한 콘텐츠의 완전성이나 정확성을 보장하지 않습니다.
        </p>
      </section>

      <section>
        <h2 className="text-base font-semibold mb-2">5. 이용자의 책임</h2>
        <ul className="list-disc pl-5 space-y-1">
          <li>이용자는 레스토랑 직원에게 알레르기 정보를 확인할 책임이 있습니다</li>
          <li>이용자는 AI 분석이 모든 알레르기 유발 성분이나 식이 관련 사항을 감지하지 못할 수 있음을 인지합니다</li>
          <li>이용자는 특히 음식 알레르기와 관련하여 자신의 책임 하에 본 서비스를 이용합니다</li>
          <li>이용자는 생명에 위협이 되는 알레르기 관련 결정을 본 서비스에만 의존하지 않습니다</li>
        </ul>
      </section>

      <section>
        <h2 className="text-base font-semibold mb-2">6. 결제 및 환불</h2>
        <p>
          트립 패스와 스캔 크레딧은 Stripe를 통해 처리되는 일회성 결제입니다. 트립 패스는 명시된 기간
          (7일 또는 30일) 종료 시 만료됩니다. 스캔 크레딧은 만료되지 않습니다. 환불 요청은 구매일로부터
          7일 이내에 신청할 수 있습니다.
        </p>
      </section>

      <section>
        <h2 className="text-base font-semibold mb-2">7. 약관의 변경</h2>
        <p>
          본 약관은 수시로 갱신될 수 있습니다. 변경 후에도 서비스를 계속 이용하는 경우 갱신된
          약관에 동의한 것으로 간주됩니다.
        </p>
      </section>

      <section>
        <h2 className="text-base font-semibold mb-2">8. 문의</h2>
        <p>
          본 약관에 관한 문의는 앱 또는 웹사이트를 통해 TransTaste 팀에 연락해 주시기 바랍니다.
        </p>
      </section>
    </>
  );
}

export default function TermsPage() {
  const { t, locale } = useTranslation();

  return (
    <main id="page-top" className="min-h-screen bg-cream pb-28">
      <div className="max-w-prose mx-auto px-5 pt-14 pb-8">
        <p className="mengto-kicker mb-2 text-[9px] font-extrabold text-coral">Document · terms</p>
        <h1 className="mb-6 text-3xl font-bold text-brown-dark">{t("legal.termsTitle")}</h1>
        <p className="text-xs text-brown-medium mb-8">{t("legal.lastUpdated")}</p>

        <div className="prose-sm text-brown-dark space-y-6 text-sm leading-relaxed">
          {locale === "ko" ? <TermsKo /> : <TermsEn />}
        </div>

        <div className="mt-8 pt-4 border-t border-brown-light/10">
          <Link href="/privacy" className="text-sm text-coral hover:underline">
            {t("legal.linkToPrivacy")}
          </Link>
          <a href="#page-top" className="float-right text-sm text-coral hover:underline">
            {locale === "ko" ? "맨 위로" : "Back to top"}
          </a>
        </div>
      </div>
    </main>
  );
}
